source-repository-package
  type: git
  location: https://github.com/tweag/ouroboros-consensus.git
  tag: 6f63ad5b690ae793fef97cf48d6792d602f5aed3
  --sha256: sha256-EuU6UZ1hIzznkKUMttJ1+2KduL9e5wlBekDMPdEp4Mc=
  subdir:
    .

source-repository-package
  type: git
  location: https://github.com/tweag/ouroboros-network.git
  tag: cb242cb70388304904ca0aaa50825db7c64be0fe
  --sha256: sha256-Dt/pUtW6FJdBVbM+56k6AP4fVz4xpzp9pbwg6gmWnJs=
  subdir:
    ./cardano-diffusion
    ./monoidal-synchronisation
    ./network-mux
    ./ouroboros-network
